### ISSUE TITLE
User Mgt: Group identifier was displayed instead of display name

### ISSUE THREAD

**Issue by barbacenasmc** [barbacenasmc/armis-issues#15]
Pre-condition:
- There are filed and declared records that already exists in the Records Management Site.
- Users that filed and declared the records belong to a designation group.
- Report database was already filled with current data.

Steps to replicate:

1. Generate a user management report.

Actual result: Group identifier was displayed instead of display name

Expected result: Group name should be displayed because it is more easy to understand.

![image](https://cloud.githubusercontent.com/assets/7791554/8924436/428b8f88-3530-11e5-8b5d-343675754e05.png)

**Comment by emarino0411** [comment]
Fixed. Ready for next release.

**Comment by barbacenasmc** [comment]
Retesting of this issue was blocked due to corrupted report generated.

**Comment by barbacenasmc** [comment]
Issue is still not resolved because the agency site role was displayed instead of the designation where the user belongs.
![image](https://cloud.githubusercontent.com/assets/7791554/10931002/8046702e-82fe-11e5-97b8-f1549f465cad.png)

**Comment by emarino0411** [comment]
Can you access a document if you dont have the rights on that site?

**Comment by barbacenasmc** [comment]
No you can't. But the expectation about this is to display the designation where the user belongs. (Though designation is not required for users. So if there is no designation available, this will be "N/A")

**Comment by emarino0411** [comment]
What if the user has multiple designations?

**Comment by emarino0411** [comment]
Fixed by updating trigger.

**Comment by barbacenasmc** [comment]
That's a good question Ms. May, actually the client has not mentioned anything about that scenario. As of the moment, we can we use the latest designation available instead? There might be some situations that a user has been promoted to another level of designation. So in doing such, we might limit conflicts in the future. Thanks :+1:

**Comment by emarino0411** [comment]
There are no timestamp for the update of the designation table. See groups table.

**Comment by barbacenasmc** [comment]
Hi Ms. May, I'm having a problem with the test server. I tried both prod and non-prod setup but still I can't retrieve any data. Can you help me? Thanks..

**Comment by barbacenasmc** [comment]
Hi Ms. May, no need for help for I found that the table for usermanagement was missing. So I re-opened the latest copy of the sql file and re-executed it. It succeed but I found that our old issue about the repeating read action exists again.

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
